const events = [
    {
        _id: '1',
        title: 'Live Concert: Wireless Beats',
        imageUrl: '/images/concert.jpg',
        description: 'Experience an immersive listening journey with our live concert event. Featuring state-of-the-art Bluetooth technology, high-quality AAC audio, and interactive experiences to connect with your favorite music like never before.',
        organizer: 'Apple',
        category: 'Music',
        price: 89.99,
        seatsAvailable: 1000,
        rating: 4.5,
        numReviews: 12,
    },
    {
        _id: '2',
        title: 'Tech Talk: iPhone 11 Pro Innovations',
        imageUrl: '/images/techtalk.jpg',
        description: 'Join us for a deep dive into the iPhone 11 Pro. Discover the transformative triple-camera system and significant leaps in battery life and performance.',
        organizer: 'Apple',
        category: 'Technology',
        price: 599.99,
        seatsAvailable: 500,
        rating: 4.0,
        numReviews: 8,
    },
    {
        _id: '3',
        title: 'Photography Workshop: Canon EOS 80D',
        imageUrl: '/images/workshop.jpg',
        description: 'Explore the Canon EOS 80D with hands-on guidance in our workshop. Learn about its versatile imaging specs, robust focusing systems, and intuitive design from industry experts.',
        organizer: 'Cannon',
        category: 'Photography',
        price: 929.99,
        seatsAvailable: 15,
        rating: 3,
        numReviews: 12,
    },
    {
        _id: '4',
        title: 'Gaming Marathon: Playstation 4 Pro Showdown',
        imageUrl: '/images/gaming.jpg',
        description: 'The ultimate gaming marathon is here. Join us for non-stop PlayStation action, featuring HD movies, music, and the best games on the market.',
        organizer: 'Sony',
        category: 'Gaming',
        price: 399.99,
        seatsAvailable: 200,
        rating: 5,
        numReviews: 12,
    },
    {
        _id: '5',
        title: 'Esports Tournament: Ultimate Gaming Challenge',
        imageUrl: '/images/esports.jpg',
        description: 'Get ready for the Logitech LIGHTSYNC Esports Tournament. Customize your play with programmable buttons and experience gaming like never before.',
        organizer: 'Logitech',
        category: 'Gaming',
        price: 49.99,
        seatsAvailable: 100,
        rating: 3.5,
        numReviews: 10,
    },
    {
        _id: '6',
        title: 'Smart Home Seminar: Amazon Echo Dot Masterclass',
        imageUrl: '/images/smarthome.jpg',
        description: 'Meet Echo Dot in our smart home seminar. Discover compact design and how it fits into your smart home ecosystem, offering hands-free help in any room.',
        organizer: 'Amazon',
        category: 'Technology',
        price: 29.99,
        seatsAvailable: 0, // Could indicate sold out or not available
        rating: 4,
        numReviews: 12,
    },
];

export default events;
