# fly.toml app configuration file generated for supertoken-core on 2024-12-11T19:36:23+13:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'auis-supertokens'
primary_region = 'syd'

[build]
  image = 'registry.supertokens.io/supertokens/supertokens-postgresql'

[http_service]
  internal_port = 3567
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512