# fly.toml app configuration file generated for auis-supertokens on 2024-12-11T18:44:14+13:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'auis-supertokens'
primary_region = 'syd'

[build]
  image = 'registry.supertokens.io/supertokens/supertokens-postgresql'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
