version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    expose:
      - 5432
    command: ["postgres", "-c", "listen_addresses=0.0.0.0"]

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  supertokens:
    image: supertokens/supertokens-postgresql
    ports:
      - 3567:3567
    expose:
      - 3567
    environment:
      environment:
        - POSTGRESQL_CONNECTION_URI=${POSTGRESQL_CONNECTION_URI}
      LOG_LEVEL: ERROR
      POSTGRESQL_CONNECTION_URI: POSTGRESQL_CONNECTION_URI
    restart: always