version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: AUIS
      POSTGRES_PASSWORD: GuryIsGoat
      POSTGRES_DB: AUIS
    ports:
      - 5435:5432
    expose:
      - 5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
