version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: AUIS
      POSTGRES_PASSWORD: GuryIsGoat
      POSTGRES_DB: AUIS
    ports:
      - 5432:5432
    expose:
      - 5432
    command: ["postgres", "-c", "listen_addresses=0.0.0.0"]

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  supertokens:
    image: supertokens/supertokens-postgresql
    ports:
      - 3567:3567
    environment:
      POSTGRESQL_CONNECTION_URI: "postgresql://db:5432/AUIS?user=AUIS&password=GuryIsGoat"
    restart: always