name: Build DEV

on:
  push:
    branches-ignore:
      - "main"

jobs:
  BuildWeb:
    runs-on: ubuntu-latest
    environment: DEV
    defaults:
      run:
        working-directory: ./web

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: yarn

      - run: yarn test

      - name: Build
        run: yarn build

  BuildStrapi:
    runs-on: ubuntu-latest
    environment: DEV
    defaults:
      run:
        working-directory: ./strapi

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: yarn

      - name: Build
        run: yarn build
