name: Fly Deploy AUIS production

on:
  push:
    branches:
      - main

jobs:
  deploy-web:
    name: Deploy Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --config fly.auis.toml --build-secret VITE_CLERK_PUBLISHABLE_KEY=${{ secrets.VITE_STRIPE_PUBLISHABLE_KEY }}
        working-directory: ./web
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_AUIS_API_TOKEN }}

  deploy-api:
    name: Deploy Api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --config fly.auis.toml
        working-directory: ./api
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_AUIS_API_TOKEN }}

  deploy-strapi:
    name: Deploy Strapi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --config fly.auis.toml
        working-directory: ./strapi
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_STRAPI_AUIS_API_TOKEN }}

  deploy-supertokens:
    name: Deploy Supertokens
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --config fly.auis.toml
        working-directory: ./supertoken-core
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_SUPERTOKENS_AUIS_API_TOKEN }}

  deploy-database:
    name: Deploy Database
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --config fly.auis.toml
        working-directory: ./database
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_SUPERTOKENS_AUIS_API_TOKEN }}
