name: Fly Deploy Production

on: [workflow_dispatch]

jobs:
  deploy-web:
    name: Deploy Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --config fly.staging.toml --build-secret VITE_API_URL=${{ secrets.VITE_API_PRODUCTION_URL }} --build-secret VITE_STRAPI_URL=${{ secrets.VITE_STRAPI_PRODUCTION_URL }} --build-secret VITE_CLERK_PUBLISHABLE_KEY=${{ secrets.VITE_CLERK_PUBLISHABLE_KEY }}
        working-directory: ./web
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_PRODUCTION_API_TOKEN }}

  deploy-api:
    name: Deploy Api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --config fly.production.toml --build-secret DATABASE_HOST=${{ secrets.DATABASE_HOST }} --build-secret DATABASE_PORT=${{ secrets.DATABASE_PORT }} --build-secret DATABASE_USERNAME=${{ secrets.DATABASE_PORT }} --build-secret DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}
        working-directory: ./api
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_PRODUCTION_API_TOKEN }}

  deploy-strapi:
    name: Deploy Strapi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --config fly.production.toml
        working-directory: ./strapi
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_STRAPI_PRODUCTION_API_TOKEN }}
